### ISSUE TITLE
Connection trouble task 5

### ISSUE THREAD

**Issue by Narror** [romankuchin/ica0002-2020#10]
Hi,

It seems my **_hosts_** file is not recognised when i run `ansible-playbook test_ansible.yaml`.

I have these warnings:
```
[WARNING]: Ansible is being run in a world writable directory (/media/narror/Data_D/mes_documents/1_Ecole/ENSIBS/CYBER_3_Tallin/IT_Infra/ica0002), ignoring it as an
ansible.cfg source. For more information see https://docs.ansible.com/ansible/devel/reference_appendices/config.html#cfg-in-world-writable-dir

[WARNING]: No inventory was parsed, only implicit localhost is available

[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

[WARNING]: Could not match supplied host pattern, ignoring: my_vm

PLAY [Ansible connection test] ***************************************************************************
skipping: no hosts matched

PLAY RECAP *********************************************************************************************


```
The first one doesn't seem serious to me but I don't know how to solve the 3 others.

There is my work folder.
```
├── ica0002
│   ├── ansible.cfg
│   ├── .git
│   │   ├── branches
│   │   ├── COMMIT_EDITMSG
│   │   ├── config
│   │   ├── description
│   │   ├── FETCH_HEAD
│   │   ├── HEAD
│   │   ├── hooks
│   │   ├── index
│   │   ├── info
│   │   ├── logs
│   │   ├── objects
│   │   ├── packed-refs
│   │   └── refs
│   ├── hosts
│   ├── README.md
│   ├── roles
│   │   └── test_connection
│   └── test_ansible.yaml
└── TP_ansible_venv
```

I push all my configuration on : https://github.com/Narror/ica0002

Thanks :)

**Comment by stadov** [comment]
As the first line in the log says, you're giving too much permissions in the directory and as a reaction Ansible ignores the provided .cfg file.

Running the following command will give "Others" only read access, which should be enough to satisfy Ansible:
`chmod o=r -R /media/narror/Data_D/mes_documents/1_Ecole/ENSIBS/CYBER_3_Tallin/IT_Infra/ica0002 `

This could require root privileges, in which case just add sudo at the start of the command.

**Comment by Narror** [comment]
Thanks, it all good.
So I didn't quite understand the first warning.
The problem came from my fstab that was mounting my hard drive with too many rights.
