### ISSUE TITLE
[Lab 2] Task 4 - Logging formatting question.

### ISSUE THREAD

**Issue by stadov** [romankuchin/ica0002-2020#16]
I've been trying to figure out Lab 2 Task 4 for a while now. Seemingly it requires you to configure Ansible so that it would log only the path and status every time the playbook is run, only if the file was affected. At the moment, the best I've gotten is logging the whole stdout, unfiltered, and messed around with Callbacks, which seem to be way out of scope for this task.

Any tips on this?

**Comment by hudolejev** [comment]
Hello.

The idea of the task was just to manually list the files that were changed on server. Ansible prints that info in the output, this task is about inspecting and understanding the Ansible output, you got that part right. We didn't expect you to parse the output automatically though.

We'll update the task description to be more clear.

---

But I like your approach (: The direction is correct. If I'd need to process the Ansible output automatically I'd use the JSON output callback as JSON seems to be the simplest format to parse.

```
ANSIBLE_STDOUT_CALLBACK=json ansible-playbook playbook.yaml > output.json
```

Will dump the output to `output.json`. Then I'd use Python script (probably is a better choice here) or `jq` to parse it, for example,

```
cat output.json | jq -r '.plays[0].tasks[1:]|.[].hosts.vm-1.invocation.module_args.diff'
```

It will show a diff per task, if any, and you can easily fetch the file names and derive the file state from there.

But again, this is not required in the task.

**Comment by stadov** [comment]
Thank you, that makes more sense.

I was thinking about using other programs to filter out the output aswell, but the task at the moment requires only using `ansible-playbook lab02...`, I tried adding some "local" tasks which would filter the output, but that required sudo password. I thought that would complicate this task too much for now, maybe in a future task.

Thanks for the extensive answer and clarification.
