### ISSUE TITLE
Any special formating I should be aware before editing ~\.ssh\auhtorized_keys

### ISSUE THREAD

**Issue by pierremarielechevalier** [romankuchin/ica0002-2020#18]
Hi, 
I've changed my control-node since last week and updated my ssh keys onto gihtub. Changes have been taken into account on [the students pannel](http://193.40.156.86/students.html) but not directly onto the VM (I can't ssh using the new ssh key but I can still do it using the old one). 

I ssh'd into it using my old control node to change ~\.ssh\authorized_keys and here are the orginal content of the file 
ssh-rsa _ssh-rsa-key_
ssh-ed25519 _old_control_node_ssh_key_  _githubname_

I've left the ssh-rsa key in place since I assume it have something to do with the way the VM are administered and only changed the second key to my own new public key.

Does I have to also add my github account name after it or can I just leave the comment of the key  ? 

Thanks

**Comment by romankuchin** [comment]
Structure of keys there:
<type> <key> <key-name>
<key-name> can be pretty much anything, it's not used for authentication in current setup. Can be empty as well.
Each key in authorized_keys should start with new line, so we have kind of a table there.

**Comment by hudolejev** [comment]
Also, I'd recommend to add both public keys to GitHub if you plan to use both. Once new machines are deployed all keys from your GitHub account should be added there, so you can use any of then to log in.

But this only applies to new machines. Existing ones need to be updated explicitly.
