### ISSUE TITLE
Lab 03 Install dependencies with command line

### ISSUE THREAD

**Issue by matry18** [romankuchin/ica0002-2020#22]
In lab 03 task 2 we have to install the app dependencies and in the link with the AGAMA installation instructions, it is suggested to use the following command: apt install python3-flask-sqlalchemy
But how do I send a send such a command?

The only solution I can come up with is this:
- name: install app dependencies in directory
  apt:
    pkg:
      - python3
      - flask
      - sqlalchemy

Should it be done like this or am I missing a point?

**Comment by romankuchin** [comment]
name: install app dependencies in directory
apt:
  name: python3-flask-sqlalchemy

Based on https://docs.ansible.com/ansible/latest/modules/apt_module.html

if you unsure about packages names, you can login with ssh to your VM and check with "apt-cache search <name>" if that package is available.
