### ISSUE TITLE
ansible-playbook command returns unexpected error:  cannot pickle 'module' object

### ISSUE THREAD

**Issue by dmitriknjazev** [romankuchin/ica0002-2020#40]
The error returned when trying to launch any playbook.

It work perfectly all the time, but after OS update I started to get 
ERROR! Unexpected Exception, this is probably a bug: cannot pickle 'module' object. 

ansible --version returns 2.9.0

when running example form the very first lab:

ansible-playbook test_ansible.yaml   

returns

PLAY [Ansible connection test] ***************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************
ERROR! Unexpected Exception, this is probably a bug: cannot pickle 'module' object
to see the full traceback, use -vvv

Tried to reinstall ansible, and it did not help.
What can I do to fix the problem?

**Comment by romankuchin** [comment]
Your Ansible version doesn't work with your Python3 version.
Easiest fix:
Instead of ~/ansible-venv/bin/pip install ansible==2.9
use ~/ansible-venv/bin/pip install ansible==2.9.12

**Comment by dmitriknjazev** [comment]
Fixed. Thanks you very much!

**Comment by hudolejev** [comment]
Any Ansible version starting from 2.9.1 should work according to this: https://github.com/ansible/ansible/issues/63973
