### ISSUE TITLE
[Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by oxuss** [romankuchin/ica0002-2020#44]
I randomly have this error when installing a new program.
Sometimes just running the playbook a second time works.

From ansible output: `fatal: [vm-2]: FAILED! => {"changed": false, "cmd": "/usr/bin/dpkg --field /opt/telegraf_1.15.3-1_amd64.deb Package", "msg": "[Errno 12] Cannot allocate memory", "rc": 12}`

**Comment by romankuchin** [comment]
That means you need more RAM for your VM.
We will change VMs sizes then.
Quick solution for you would be to choose another VM:
```
ubuntu@oxuss-1:~$ free -h
              total        used        free      shared  buff/cache   available
Mem:           481M        227M         34M        1.1M        219M        248M
```

```
ubuntu@oxuss-2:~$ free -h
              total        used        free      shared  buff/cache   available
Mem:           481M        430M        6.9M        696K         43M         37M
```

VM-1 has plenty of RAM still available, while it's only 37MB on VM-2.

**Comment by romankuchin** [comment]
All VMs recreated with x2 RAM.
