### ISSUE TITLE
Prometheus generates nubmer of 512MB files and causes memory usage error

### ISSUE THREAD

**Issue by dmitriknjazev** [romankuchin/ica0002-2020#57]
When trying to run ansible-playbook fatal error returned:

fatal: [vm-1]: UNREACHABLE! => {"changed": false, "msg": "mkdir: cannot create directory '/home/ubuntu/.ansible/tmp/ansible-tmp-1606669449.056662-93890-150021066228916': No space left on device\n", "unreachable": true}

finding the biggest files by running on my vm-1

find / -type f -size +100000k -exec ls -lh {} ; | awk '{ print $9 ": " $5 }'

and here is the output.

/var/lib/prometheus/metrics2/01ER5VF6AR1BKWW6YD87B0AAC6/chunks/000001: 512M
/var/lib/prometheus/metrics2/wal/000051: 256M
/var/lib/prometheus/metrics2/wal/000104: 256M
/var/lib/prometheus/metrics2/01ER2Z7QXC4H3QD369ESV9V94Y/chunks/000001: 145M
/var/lib/prometheus/metrics2/01ER5V9GTJVGW3CGHYCM35HWXT/chunks/000001: 265M
/var/lib/prometheus/metrics2/01ER2ZK7XQRYRBXJQYE3MKTYGJ/chunks/000001: 512M
/var/lib/prometheus/metrics2/01ER5WJ3K4P3C81KNA5ZEDEDDF/chunks/000001: 185M
/var/lib/prometheus/metrics2/01ER5WQPJ2YJXC3DAYYBC2T8XW/chunks/000001: 370M
/var/lib/prometheus/metrics2/01ER2ZSVB9WFVPY39GR4JQ11H0/chunks/000003: 134M
/var/lib/prometheus/metrics2/01ER2ZSVB9WFVPY39GR4JQ11H0/chunks/000001: 512M
/var/lib/prometheus/metrics2/01ER2ZSVB9WFVPY39GR4JQ11H0/chunks/000002: 512M
/var/lib/prometheus/metrics2/01ER5V3Z2S059MW0J3MX8QFV12/chunks/000001: 133M
/var/lib/prometheus/metrics2/01ER2ZDAX38AAV0BQPHA911ZRX/chunks/000001: 290M
/var/lib/prometheus/metrics2/01ER5SQNE7M6H43Q04YSA87QEG/chunks/000003: 512M
/var/lib/prometheus/metrics2/01ER5SQNE7M6H43Q04YSA87QEG/chunks/000004: 511M
/var/lib/prometheus/metrics2/01ER5SQNE7M6H43Q04YSA87QEG/chunks/000001: 511M
/var/lib/prometheus/metrics2/01ER5SQNE7M6H43Q04YSA87QEG/chunks/000002: 512M

How to avoid generation chunk files by prometheus?

**Comment by romankuchin** [comment]
I'd check for `--storage.tsdb.retention.time`
Docs: https://prometheus.io/docs/prometheus/latest/storage/#operational-aspects
Probably you don't need to store metrics for 2 weeks, 2 hours would be enough.
