### ISSUE TITLE
Cannot create Agama docker container on second machine

### ISSUE THREAD

**Issue by AlekefromKz** [romankuchin/ica0002-2020#58]
Good afternoon! 

I tried to run the same playbook from lab 12 for my second machine, to have dockerized agama there as well. Grafana docker container was successfully installed, but I have some problems with Agama. 

Here are the mistakes. Have no idea what to do:(

![image](https://user-images.githubusercontent.com/61705560/100746112-f45b8580-33e8-11eb-83a6-9625eeba84ed.png)

**Comment by romankuchin** [comment]
Error is pretty clear if you read it  - "Failure in name resolution".
If you run just "alpine" container of that VM, will it be able to resolve addresses?

**Comment by Narror** [comment]
I've fix this building docker manually with `ubuntu@narror-2:/opt/agama$ sudo docker build --network=host -t agama .`

**Comment by AlekefromKz** [comment]
The problem was in DNS configurations. You should allow 172.15.0.0/16 as well. Thanks to Roman for explanation.
