### ISSUE TITLE
cant' reach VMs

### ISSUE THREAD

**Issue by nanokoo** [romankuchin/ica0002-2020#60]
is anything wrong with VMs? can't ssh

**Comment by romankuchin** [comment]
Please, provide more details.

**Comment by nanokoo** [comment]
from Terminal, web and via running ansible playbook 
![Screenshot 2020-12-04 at 11 03 51](http
<img width="474" alt="Screenshot 2020-12-04 at 11 07 45" src="https://user-images.githubusercontent.com/43971741/101144503-17707a00-3621-11eb-884c-564dea476a86.png">
s://user-images.githubusercontent.com/43971741/101144501-163f4d00-3621-11eb-9be8-e1e660519a13.png)
<img width="510" alt="Screenshot 2020-12-04 at 11 05 15" src="https://user-images.githubusercontent.com/43971741/101144502-17707a00-3621-11eb-95ff-82d017708222.png">

**Comment by romankuchin** [comment]
You're using wrong port. Please, check the correct numbers here: http://193.40.156.86/vms.html

**Comment by nanokoo** [comment]
great! 👿 when was it changed
thanks, problem solved.
