### ISSUE TITLE
No module named 'dns' error

### ISSUE THREAD

**Issue by MrLightWood** [romankuchin/ica0002-2020#62]
Good day!
I was doing lab 14 and encountered this interesting error. When using nsupdate module my Ansible gives this error
![image](https://user-images.githubusercontent.com/17985968/101395304-6db81400-38d2-11eb-9208-bdd5baa8a157.png)

Here is my code I execute
![image](https://user-images.githubusercontent.com/17985968/101395341-7c063000-38d2-11eb-9128-82457dbd77f0.png)

It's not only me who has this problem, my friend is facing it too. What are we doing wrong?

**Comment by romankuchin** [comment]
Please, read the next line: Failed to import library dnspython.
For managing Docker with Ansible you need to install `python3-docker`.
Same for DNS, you need to install additional package called `python3-dnspython`.

**Comment by MrLightWood** [comment]
Heeey, that works. Thanks!
I was installing dnspython manually on a machine with pip install command. And as I see the answer was easier than I expected
