### ISSUE TITLE
Discord channel link

### ISSUE THREAD

**Issue by robieerto** [romankuchin/ica0002-2020#66]
Hi,
could you please share the Discord invitation link again?

Thanks a lot.

**Comment by ellawerthan** [comment]
This should be good for the next 24 hours: https://discord.gg/aazDgVJR

**Comment by paktalin** [comment]
Hi! Same request again: could you share a new discord link, please? @ellawerthan

**Comment by romankuchin** [comment]
https://discord.gg/CJz47j2j

**Comment by marguspeet** [comment]
Hi, could I get the Discord invitation link please.

**Comment by romankuchin** [comment]
https://discord.gg/2V8rK2nM
