### ISSUE TITLE
Backup server does not update ssh keys

### ISSUE THREAD

**Issue by MrLightWood** [romankuchin/ica0002-2020#67]
Good evening!
As you know, our machines are reset every week. So, when I restore my machines with Ansible playbook I create backup users with new ssh keys. I think that the backup server does not update old ssh keys to new ones. That's why I can't do ssh to the backup server using the backup user. Can you please help me with that issue?

**Comment by romankuchin** [comment]
Does this look correct:
```# cat /home/MrLightWood/.ssh/authorized_keys
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDJGfYNLSlfrVjSjz+d0TQaQ+p7GZIdIColf3Ha2N4TaxOXAmrAD7tfmz7IYr5oBdDpEwgJDo5zPke0en0VjzBU86uyANxnswnwtBbjY3Roz2ZjUzr906Aw03SQEAqLse4h70D2Bn9XkobCQMu/qHK0AB2LFA1M5IYQUoXAa7pf+mrpOPbd0urNMqDvQKnMZxXRm946e7wge3F42I3tH/2jn/sweXsqoElWW5sO3bqPrAI5PD+1xhbz9iLXM/t/wJDmxkRWjlNtj8WeJtmne2Z6bEfBWCZHHosI6gBUm/WSsj3YNiWsvghrQXYCGpra3YewTOh/R5OELaFf2YVmoAcD ansible-generated on mrlightwood-1
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDM5cHi3MOwr4BzFOKVKEGT3obKARxRMmzQGzfM5vAzlbt+DVfSf/wafue3jQVyTHfQuVEEhFkhwZNbWN9k2e//PLhlICOoYozu0MRBvBBv/Tw9a6r10PO3HZ6TR7cBvYZB9Sb2WCjT6DaPq2dEGjilObpw6gEY4fvjj/vWLU5P9k46CqV2VM43g6mgJr/5M5RW9WLAoOMchTaviBT2n0UbGxvE1I+7y2LhJ12TjpPoEX6knxQzgEY6PdunkJa3AIxuzdhEcVZ11r5i4KyVoYYZ07mKrp9mGDA8oeQFqrqwB7nbtc7wPKqmrC+22auFB/mIRSV+7dPYxcasdG2AlTv3 ansible-generated on mrlightwood-2
```

**Comment by MrLightWood** [comment]
> Does this look correct:
> 
> ```
> ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDJGfYNLSlfrVjSjz+d0TQaQ+p7GZIdIColf3Ha2N4TaxOXAmrAD7tfmz7IYr5oBdDpEwgJDo5zPke0en0VjzBU86uyANxnswnwtBbjY3Roz2ZjUzr906Aw03SQEAqLse4h70D2Bn9XkobCQMu/qHK0AB2LFA1M5IYQUoXAa7pf+mrpOPbd0urNMqDvQKnMZxXRm946e7wge3F42I3tH/2jn/sweXsqoElWW5sO3bqPrAI5PD+1xhbz9iLXM/t/wJDmxkRWjlNtj8WeJtmne2Z6bEfBWCZHHosI6gBUm/WSsj3YNiWsvghrQXYCGpra3YewTOh/R5OELaFf2YVmoAcD ansible-generated on mrlightwood-1
> ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDM5cHi3MOwr4BzFOKVKEGT3obKARxRMmzQGzfM5vAzlbt+DVfSf/wafue3jQVyTHfQuVEEhFkhwZNbWN9k2e//PLhlICOoYozu0MRBvBBv/Tw9a6r10PO3HZ6TR7cBvYZB9Sb2WCjT6DaPq2dEGjilObpw6gEY4fvjj/vWLU5P9k46CqV2VM43g6mgJr/5M5RW9WLAoOMchTaviBT2n0UbGxvE1I+7y2LhJ12TjpPoEX6knxQzgEY6PdunkJa3AIxuzdhEcVZ11r5i4KyVoYYZ07mKrp9mGDA8oeQFqrqwB7nbtc7wPKqmrC+22auFB/mIRSV+7dPYxcasdG2AlTv3 ansible-generated on mrlightwood-2
> ```

Yes, the keys look correct. I understood what the reason was. The backup server IP has changed, that's why I couldn't connect. Now I will be monitoring the backup server IP too :D
