### ISSUE TITLE
can't ssh to backup server

### ISSUE THREAD

**Issue by nanokoo** [romankuchin/ica0002-2020#68]
can I have public keys from backup server to check whether it matches to generated ones or not

**Comment by nanokoo** [comment]
<img width="480" alt="Screenshot 2020-12-15 at 19 07 42" src="https://user-images.githubusercontent.com/43971741/102247802-1ab11300-3f09-11eb-9315-ad3a23ccafac.png">
<img width="310" alt="Screenshot 2020-12-15 at 19 08 25" src="https://user-images.githubusercontent.com/43971741/102247811-1c7ad680-3f09-11eb-8b2c-b63903a6a525.png">
<img width="369" alt="Screenshot 2020-12-15 at 19 09 21" src="https://user-images.githubusercontent.com/43971741/102247812-1c7ad680-3f09-11eb-9565-90b8e1f48fe2.png">

**Comment by romankuchin** [comment]
Share the output of `host backup.covid20.io`. It's should be 192.168.42.156.

**Comment by nanokoo** [comment]
now Vms are renewed again but host for backup was `192.168.42.31` as stated in lab9

**Comment by romankuchin** [comment]
Sorry, I forgot to update the lab text after our backup server was dead.

**Comment by nanokoo** [comment]
Thanks
